### ISSUE TITLE
Doesn't work even for https://*.medium.com/*

### ISSUE THREAD

**Issue by ssi-anik** [mesuutt/read-medium-extension#4]
Can you read the article? 
https://hafiqiqmal93.medium.com/trick-how-to-separate-locust-for-admin-and-viewer-e4381f84ad

**Comment by UsamaKarim** [comment]
Not even direct medium url

![image](https://user-images.githubusercontent.com/64292174/110660641-91e30400-81e5-11eb-891e-2d64d2cebde2.png)

**Comment by UsamaKarim** [comment]
![image](https://user-images.githubusercontent.com/64292174/110663927-c4423080-81e8-11eb-808e-ff1e5f92ba0b.png)

**Comment by ssi-anik** [comment]
@UsamaKarim please try reading 3 more articles from the author. at let us know.

**Comment by UsamaKarim** [comment]
> @UsamaKarim please try reading 3 more articles from the author. at let us know.

You might need to disable your AdBlock. Working fine for me. [You need to click on _**Read for free**_]

![image](https://user-images.githubusercontent.com/64292174/110665922-a675cb00-81ea-11eb-9c5d-b9442398740a.png)

**Comment by ssi-anik** [comment]
Okay, will follow your steps tomorrow morning and inform in this thread. 
BTW, Should I have to stay logged out all the time?

Yes, I get it now. Thanks.

https://github.com/mesuutt/read-medium-extension/blob/5815834d889775cca20520e53920384dbc158364/content.js#L30-L35
